# Generated by Django 3.0.5 on 2020-04-12 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaddlePlan',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('billing_type', models.CharField(max_length=255)),
                ('billing_period', models.PositiveIntegerField()),
                ('trial_days', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PaddleSubscription',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_id', models.PositiveIntegerField()),
                ('user_email', models.EmailField(max_length=254)),
                ('marketing_consent', models.BooleanField()),
                ('update_url', models.CharField(max_length=255)),
                ('cancel_url', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('signup_date', models.DateTimeField()),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_paddle.PaddlePlan')),
            ],
        ),
        migrations.CreateModel(
            name='PaddleRecurringPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_prices', to='django_paddle.PaddlePlan')),
            ],
            options={
                'default_related_name': 'recurring_prices',
            },
        ),
        migrations.CreateModel(
            name='PaddleInitialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_prices', to='django_paddle.PaddlePlan')),
            ],
            options={
                'default_related_name': 'initial_prices',
            },
        ),
    ]
